<a href="https://colab.research.google.com/github/AarushiShahi/AI.LAB002/blob/main/Week_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
def is_goal(board):
    return board == [[1, 2, 3], [4, 5, 6], [7, 8, 0]]

def get_possible_moves(empty_tile):
    moves = []
    row, col = empty_tile
    directions = [(1, 0), (-1, 0), (0, 1), (0, -1)]  # Down, Up, Right, Left

    for dr, dc in directions:
        new_row, new_col = row + dr, col + dc
        if 0 <= new_row < 3 and 0 <= new_col < 3:
            moves.append((new_row, new_col))

    return moves

def make_move(board, empty_tile, new_empty_tile):
    new_row, new_col = new_empty_tile
    new_board = [row[:] for row in board]  # Create a copy of the board
    new_board[empty_tile[0]][empty_tile[1]] = new_board[new_row][new_col]
    new_board[new_row][new_col] = 0  # Move the empty tile
    return new_board, new_empty_tile

def dfs(board, empty_tile, path):
    stack = [(board, empty_tile, path)]
    visited = set()

    while stack:
        current_board, current_empty_tile, current_path = stack.pop()

        if is_goal(current_board):
            return current_path

        visited.add(tuple(map(tuple, current_board)))

        for move in get_possible_moves(current_empty_tile):
            new_board, new_empty_tile = make_move(current_board, current_empty_tile, move)
            if tuple(map(tuple, new_board)) not in visited:
                stack.append((new_board, new_empty_tile, current_path + [new_board]))

    return None

def get_initial_board():
    print("Enter the initial configuration of the 8-puzzle (use 0 for the empty space):")
    board = []
    for i in range(3):
        row = list(map(int, input(f"Row {i + 1} (3 numbers separated by space): ").strip().split()))
        if len(row) != 3:
            print("Invalid input. Please enter exactly 3 numbers.")
            return get_initial_board()
        board.append(row)
    return board

# Main execution flow
initial_board = get_initial_board()

empty_tile = next((i, row.index(0)) for i, row in enumerate(initial_board) if 0 in row)

solution_path = dfs(initial_board, empty_tile, [])

if solution_path:
    print("Solution path:")
    for step in solution_path:
        for row in step:
            print(row)
        print()
else:
    print("No solution found.")




Streaming output truncated to the last 5000 lines.
[2, 5, 6]
[0, 3, 1]
[4, 7, 8]

[2, 5, 6]
[3, 0, 1]
[4, 7, 8]

[2, 5, 6]
[3, 1, 0]
[4, 7, 8]

[2, 5, 0]
[3, 1, 6]
[4, 7, 8]

[2, 0, 5]
[3, 1, 6]
[4, 7, 8]

[0, 2, 5]
[3, 1, 6]
[4, 7, 8]

[3, 2, 5]
[0, 1, 6]
[4, 7, 8]

[3, 2, 5]
[1, 0, 6]
[4, 7, 8]

[3, 2, 5]
[1, 6, 0]
[4, 7, 8]

[3, 2, 0]
[1, 6, 5]
[4, 7, 8]

[3, 0, 2]
[1, 6, 5]
[4, 7, 8]

[3, 6, 2]
[1, 0, 5]
[4, 7, 8]

[3, 6, 2]
[0, 1, 5]
[4, 7, 8]

[0, 6, 2]
[3, 1, 5]
[4, 7, 8]

[6, 0, 2]
[3, 1, 5]
[4, 7, 8]

[6, 2, 0]
[3, 1, 5]
[4, 7, 8]

[6, 2, 5]
[3, 1, 0]
[4, 7, 8]

[6, 2, 5]
[3, 0, 1]
[4, 7, 8]

[6, 2, 5]
[0, 3, 1]
[4, 7, 8]

[0, 2, 5]
[6, 3, 1]
[4, 7, 8]

[2, 0, 5]
[6, 3, 1]
[4, 7, 8]

[2, 5, 0]
[6, 3, 1]
[4, 7, 8]

[2, 5, 1]
[6, 3, 0]
[4, 7, 8]

[2, 5, 1]
[6, 0, 3]
[4, 7, 8]

[2, 5, 1]
[0, 6, 3]
[4, 7, 8]

[0, 5, 1]
[2, 6, 3]
[4, 7, 8]

[5, 0, 1]
[2, 6, 3]
[4, 7, 8]

[5, 1, 0]
[2, 6, 3]
[4, 7, 8]

[5, 1, 3]
[2, 6, 0]
[4, 7, 8]

[5, 1, 3]
[2, 0, 6]
[4, 7, 8]

[5, 1, 3]
[0, 2, 6]

In [3]:

import sys
import numpy as np


class Node:
  def __init__(self, state, parent, action):
    self.state = state
    self.parent = parent
    self.action = action


class StackFrontier:
  def __init__(self):
    self.frontier = []

  def add(self, node):
    self.frontier.append(node)

  def contains_state(self, state):
    return any((node.state[0] == state[0]).all() for node in self.frontier)

  def empty(self):
    return len(self.frontier) == 0

  def remove(self):
    if self.empty():
      raise Exception("Empty Frontier")
    else:
      node = self.frontier[-1]
      self.frontier = self.frontier[:-1]
      return node


class QueueFrontier(StackFrontier):
  def remove(self):
    if self.empty():
      raise Exception("Empty Frontier")
    else:
      node = self.frontier[0]
      self.frontier = self.frontier[1:]
      return node


class Puzzle:
  def __init__(self, start, startIndex, goal, goalIndex):
    self.start = [start, startIndex]
    self.goal = [goal, goalIndex]
    self.solution = None

  def neighbors(self, state):
    mat, (row, col) = state
    results = []

    if row > 0:
      mat1 = np.copy(mat)
      mat1[row][col] = mat1[row - 1][col]
      mat1[row - 1][col] = 0
      results.append(('up', [mat1, (row - 1, col)]))
    if col > 0:
      mat1 = np.copy(mat)
      mat1[row][col] = mat1[row][col - 1]
      mat1[row][col - 1] = 0
      results.append(('left', [mat1, (row, col - 1)]))
    if row < 2:
      mat1 = np.copy(mat)
      mat1[row][col] = mat1[row + 1][col]
      mat1[row + 1][col] = 0
      results.append(('down', [mat1, (row + 1, col)]))
    if col < 2:
      mat1 = np.copy(mat)
      mat1[row][col] = mat1[row][col + 1]
      mat1[row][col + 1] = 0
      results.append(('right', [mat1, (row, col + 1)]))

    return results

  def print(self):
    solution = self.solution if self.solution is not None else None
    print("Start State:\n", self.start[0], "\n")
    print("Goal State:\n",  self.goal[0], "\n")
    print("\nStates Explored: ", self.num_explored, "\n")
    print("Solution:\n ")
    for action, cell in zip(solution[0], solution[1]):
      print("action: ", action, "\n", cell[0], "\n")
    print("Goal Reached😊")

  def does_not_contain_state(self, state):
    for st in self.explored:
      if (st[0] == state[0]).all():
        return False
    return True

  def solve(self):
    self.num_explored = 0

    start = Node(state=self.start, parent=None, action=None)
    frontier = QueueFrontier()
    frontier.add(start)

    self.explored = []

    while True:
      if frontier.empty():
        raise Exception("No solution")

      node = frontier.remove()
      self.num_explored += 1

      if (node.state[0] == self.goal[0]).all():
        actions = []
        cells = []
        while node.parent is not None:
          actions.append(node.action)
          cells.append(node.state)
          node = node.parent
        actions.reverse()
        cells.reverse()
        self.solution = (actions,  cells)
        return

      self.explored.append(node.state)

      for action, state in self.neighbors(node.state):
        if not frontier.contains_state(state) and self.does_not_contain_state(state):
          child = Node(state=state, parent=node, action=action)
          frontier.add(child)


start = np.array([[1, 2, 3], [8, 0, 4], [7, 6, 5]])
goal = np.array([[1, 2, 3], [8, 4,0], [7, 6, 5]])


startIndex = (1, 1)
goalIndex = (1, 0)


p = Puzzle(start, startIndex, goal, goalIndex)
p.solve()
p.print()

Start State:
 [[1 2 3]
 [8 0 4]
 [7 6 5]] 

Goal State:
 [[1 2 3]
 [8 4 0]
 [7 6 5]] 


States Explored:  5 

Solution:
 
action:  right 
 [[1 2 3]
 [8 4 0]
 [7 6 5]] 

Goal Reached😊
